output_dir: 
    vcf_annotation: ../../data/results/gvex/vcf_annotation/
    junction_annotation: ../../data/results/gvex/junction_annotation/
    splicing_preds: ../../data/results/gvex/splicing_predictions/
    outliers: ../../data/results/gvex/outlier_ground_truth/
    benchmark: ../../data/results/gvex/benchmark/

genome: 'hg19'
fasta: ../../data/resources/gvex/fasta_file
gtf: ../../data/resources/gvex/gtf_file
anno_pangolin: ../../data/resources/common/hg19/pangolin_db

# vcf: ../../data/resources/raw/gvex/1.GATK_calls/combine285.{vcf_id}.both.filter.adj2.vcf.gz
vcf: ../../data/resources/gvex/vcf_normalized/combine285.{vcf_id}.both.filter.adj2.vcf.gz

DROP:
    tissue_map: ../../data/resources/gvex/tissue_map_DROP.csv
    sample_annotation: ../../data/resources/gvex/DROP/sample_annotation.tsv
    version: 'v34'
    splicemap:
        working_dir: ../../data/resources/gvex/DROP/processed_data/aberrant_splicing/datasets/
    fraser1_results: ../../data/resources/gvex/DROP/fraser1/processed_results/aberrant_splicing/results/
    fraser2_results: ../../data/resources/gvex/DROP/fraser2/processed_results/aberrant_splicing/results/

fraser_version:
    - fraser2
    - fraser1
            
filtering_params:
    vcf:
        format_fields: ['GT','GQ','DP','AD']
        remove_chr: False
        min_GQ: 1 # TODO: this might be critical
        min_DP_ALT: 1 # TODO: used to be 10, but almost nothing left with this filter
        filter_long_indels: 10
    count_table:
        update_samples: True
        key_assay: 'RNA_ID'
        value_assay: 'individualID'
        subset_chroms: False
        infer_strand: False
    splicemap:
        use_faster: True
        percentile: 95
        percentile_min_read: 1
        median_cutoff: 1
    outliers:
        combinations:
            - delta_psi_cutoff: 0.3
              padjust_cutoff: 0.05
              totalCounts_cutoff: 20
        outlier_type: 'psi5__psi3__theta'
        num_junction_outliers_per_samples: 15
    absplice:
        median_n_cutoff: 10
        tpm_cutoff: 1
        count_cat_cutoff: 20
        extra_info: True
        
spliceai:
    lookup_only: False
   
method: 'kn'
event_filter: 'median_cutoff'
gtex_version: 'gtex_v7'

use_gene_tpm: False 

subset_cols_absplice_models_new: False
models:
    - mmsplice_splicemap
    - pangolin
    - pangolin_splicemaps
    - spliceai
    # - mmsplice_splicemap_ref_psi
    # - absplice_dna_no_samples
    - absplice_dna
    # - absplice_dna_custom
    - absplice_dna_custom_new


tissue_map_subset: ../../data/resources/gvex/tissue_map_main_tissue.csv

tissues_subset:
    - Brain_Amygdala
    - Brain_Anterior_cingulate_cortex_BA24
    - Brain_Caudate_basal_ganglia
    - Brain_Cerebellar_Hemisphere
    - Brain_Cerebellum
    - Brain_Cortex
    - Brain_Frontal_Cortex_BA9
    - Brain_Hippocampus
    - Brain_Hypothalamus
    - Brain_Nucleus_accumbens_basal_ganglia
    - Brain_Putamen_basal_ganglia
    - Brain_Spinal_cord_cervical_c_1
    - Brain_Substantia_nigra

    - Brain
    - All_tissues
    # - All_main_tissues

tissue_target: brain_gvex

splicemap_tissues:
    - brain_gvex

tissues:
    - Brain_Amygdala
    - Brain_Anterior_cingulate_cortex_BA24
    - Brain_Caudate_basal_ganglia
    - Brain_Cerebellar_Hemisphere
    - Brain_Cerebellum
    - Brain_Cortex
    - Brain_Frontal_Cortex_BA9
    - Brain_Hippocampus
    - Brain_Hypothalamus
    - Brain_Nucleus_accumbens_basal_ganglia
    - Brain_Putamen_basal_ganglia
    - Brain_Spinal_cord_cervical_c_1
    - Brain_Substantia_nigra

chroms:
  - 'chr1'
  - 'chr2'
  - 'chr3'
  - 'chr4'
  - 'chr5'
  - 'chr6'
  - 'chr7'
  - 'chr8'
  - 'chr9'
  - 'chr10'
  - 'chr11'
  - 'chr12'
  - 'chr13'
  - 'chr14'
  - 'chr15'
  - 'chr16'
  - 'chr17'
  - 'chr18'
  - 'chr19'
  - 'chr20'
  - 'chr21'  
  - 'chr22'
#   - 'chrX'
#   - 'chrY'